// Code generated by MockGen. DO NOT EDIT.
// Source: donation.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "github.com/FreakyGranny/launchpad-api/internal/app/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDonationImpl is a mock of DonationImpl interface
type MockDonationImpl struct {
	ctrl     *gomock.Controller
	recorder *MockDonationImplMockRecorder
}

// MockDonationImplMockRecorder is the mock recorder for MockDonationImpl
type MockDonationImplMockRecorder struct {
	mock *MockDonationImpl
}

// NewMockDonationImpl creates a new mock instance
func NewMockDonationImpl(ctrl *gomock.Controller) *MockDonationImpl {
	mock := &MockDonationImpl{ctrl: ctrl}
	mock.recorder = &MockDonationImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDonationImpl) EXPECT() *MockDonationImplMockRecorder {
	return m.recorder
}

// GetAllByUser mocks base method
func (m *MockDonationImpl) GetAllByUser(id int) ([]models.Donation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUser", id)
	ret0, _ := ret[0].([]models.Donation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUser indicates an expected call of GetAllByUser
func (mr *MockDonationImplMockRecorder) GetAllByUser(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUser", reflect.TypeOf((*MockDonationImpl)(nil).GetAllByUser), id)
}

// GetAllByProject mocks base method
func (m *MockDonationImpl) GetAllByProject(id int) ([]models.Donation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByProject", id)
	ret0, _ := ret[0].([]models.Donation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByProject indicates an expected call of GetAllByProject
func (mr *MockDonationImplMockRecorder) GetAllByProject(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByProject", reflect.TypeOf((*MockDonationImpl)(nil).GetAllByProject), id)
}
