basePath: /
definitions:
  handlers.TokenRequest:
    properties:
      code:
        type: string
    type: object
  handlers.TokenResponse:
    properties:
      token:
        type: string
    type: object
  models.User:
    properties:
      avatar:
        type: string
      first_name:
        type: string
      id:
        type: integer
      is_admin:
        type: boolean
      last_name:
        type: string
      project_count:
        type: integer
      success_rate:
        type: number
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is a launchpad backend.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Launchpad API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: get token for user
      operationId: get-token
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.TokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.TokenResponse'
      summary: Returns access token
  /user:
    get:
      description: Returns user by ID from token
      operationId: get-user-by-token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - Bearer: []
      summary: Show a current user
  /user/{id}:
    get:
      description: Returns user by ID
      operationId: get-user-by-id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - Bearer: []
      summary: Show a specific user
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
